name: Github Action Test
on:
  push:

jobs:
  action-test:
    runs-on: ubuntu-18.04
    # strategy:
    #   matrix:
    #     node-version: [12.14.0]

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: set env
        run: |
          STAGE=production
          echo "STAGE=${STAGE}" >> $GITHUB_ENV

      - name: echo production
        if: env.STAGE == 'production'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: echo staging
        if: env.STAGE == 'staging'
        run: echo "echo staging is called ${STAGE}"

      - name: Slack Noitification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                fields: 'job',
                author_name: '${{ env.STAGE }}' === 'production' ? 'deploy-prod' : 'deploy-dev',
                mention: 'here',
                if_mention: 'failure',
                color: '${{ job.status }}' === 'success' ? 'good' : 'danger',
                text: '${{ job.status }}' === 'success' ? 'Deployment is success' : 'Deployment is failed',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
