name: Github Action Test
on:
  push:

jobs:
  action-test:
    runs-on: ubuntu-18.04
    # strategy:
    #   matrix:
    #     node-version: [12.14.0]

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: set env
        run: |
          STAGE=production
          echo "STAGE=${STAGE}" >> $GITHUB_ENV

      - name: echo production
        if: env.STAGE == 'production'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: echo staging
        if: env.STAGE == 'staging'
        run: echo "echo staging is called ${STAGE}"
