name: Github Action Test
on:
  push:

jobs:
  action-test:
    runs-on: ubuntu-18.04
    # strategy:
    #   matrix:
    #     node-version: [12.14.0]

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: set env
        run: |
          STAGE=staging
          echo "STAGE=${STAGE}" >> $GITHUB_ENV

      - name: echo production
        if: ${{ env.STAGE == 'production' }}
        run: echo "echo production is called ${STAGE}"

      - name: echo staging
        if: ${{ env.STAGE == 'staging' }}
        run: echo "echo staging is called ${STAGE}"
