name: Github Action Test
on:
  pull_request:
    paths-ignore:
      - "packages/cdk/**"
      - "packages/proxy/**"
      - "packages/certbot/**"
      - "documents/**"
      - "**.md"
      - "**/k8s/**"

jobs:
  action-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.14.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display version of Node.js, npm, Yarn
        run: |
          node --version
          npm --version
          yarn --version

      - name: set env
        run: |
          STAGE=staging
          echo "STAGE=${STAGE}" >> $GITHUB_ENV

      - name: echo production
        if: ${{ env.STAGE == 'production' }}
        run: echo "echo production is called ${STAGE}"

      - name: echo staging
        if: ${{ env.STAGE == 'staging' }}
        run: echo "echo staging is called ${STAGE}"
